import {useEffect,useState} from 'react';
import {api} from '../services/api';

const groups=[['domains','Research Domains','research_domains'],['interests','Research Interests','research_interests'],['keywords','Keywords','keywords'],['technology-areas','Technology Areas','technology_areas']];
export default function Profile(){
 const [p,setP]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [academic,setAcademic]=useState({}),[org,setOrg]=useState({}),[value,setValue]=useState('');
 const [history,setHistory]=useState({title:'',description:'',start_year:'',end_year:''});
 const load=async()=>{try{setError('');setP(await api('/profile'))}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 if(!p)return <section className="card narrow"><span className="eyebrow">Researcher profile</span><h1 style={{marginTop:8}}>Build your profile</h1><p className="muted">Add your academic and research information so the platform can personalize your intelligence workspace.</p><button className="button" onClick={async()=>{try{setP(await api('/profile',{method:'POST',body:JSON.stringify({})}))}catch(e){setError(e.message)}}}>Create research profile</button>{error&&<p className="error">{error}</p>}</section>;
 const save=async()=>{try{setP(await api('/profile',{method:'PUT',body:JSON.stringify({academic,organization:org})}));setMessage('Profile saved successfully')}catch(e){setError(e.message)}};
 const add=async(path)=>{if(!value.trim())return;try{await api(`/profile/${path}`,{method:'POST',body:JSON.stringify({value:value.trim()})});setValue('');load()}catch(e){setError(e.message)}};
 const addHistory=async()=>{try{await api('/profile/research-history',{method:'POST',body:JSON.stringify({...history,start_year:history.start_year?Number(history.start_year):null,end_year:history.end_year?Number(history.end_year):null})});setHistory({title:'',description:'',start_year:'',end_year:''});load()}catch(e){setError(e.message)}};
 return <section>
  <div className="page-head"><div><span className="eyebrow">Researcher profile</span><h1>Profile</h1><p>Manage your academic background, research interests and organization.</p></div></div>
  <div className="card"><h2 style={{marginTop:0}}>Academic & organization</h2><div className="form-grid">{['academic_title','degree','institution','academic_profile_url','research_summary'].map(k=><label key={k}>{k.replaceAll('_',' ')}<input value={academic[k]??p.academic?.[k]??''} onChange={e=>setAcademic({...academic,[k]:e.target.value})}/></label>)}{['name','organization_type','website','description'].map(k=><label key={k}>{k.replaceAll('_',' ')}<input value={org[k]??p.organization?.[k]??''} onChange={e=>setOrg({...org,[k]:e.target.value})}/></label>)}</div><button className="button" onClick={save}>Save profile</button>{message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}</div>
  <div className="grid two" style={{marginTop:18}}>{groups.map(([path,title,key])=><div className="card" key={path}><h3>{title}</h3><div className="chips">{p[key]?.map((x,i)=><span className="chip" key={i}>{x}</span>)}</div><div className="inline"><input value={value} onChange={e=>setValue(e.target.value)} placeholder={`Add ${title.toLowerCase()}`}/><button className="button" onClick={()=>add(path)}>Add</button></div></div>)}</div>
  <div className="card compact"><h3>Research history</h3><div className="form-grid"><label>Title<input value={history.title} onChange={e=>setHistory({...history,title:e.target.value})}/></label><label>Description<input value={history.description} onChange={e=>setHistory({...history,description:e.target.value})}/></label><label>Start year<input type="number" value={history.start_year} onChange={e=>setHistory({...history,start_year:e.target.value})}/></label><label>End year<input type="number" value={history.end_year} onChange={e=>setHistory({...history,end_year:e.target.value})}/></label></div><button className="button" onClick={addHistory}>Add history entry</button><div className="stack compact">{p.research_history?.map(h=><div className="row" key={h.id}><div><strong>{h.title}</strong><div>{h.description}</div><small>{h.start_year||'—'} to {h.end_year||'present'}</small></div><button className="button secondary" onClick={async()=>{await api(`/profile/research-history/${h.id}`,{method:'DELETE'});load()}}>Delete</button></div>)}</div></div>
  <div className="grid two"><div className="card"><h3>Saved publications</h3><p className="muted">{p.publication_ids?.length||0} saved publications.</p></div><div className="card"><h3>Saved patents</h3><p className="muted">{p.patent_ids?.length||0} saved patents.</p></div></div>
 </section>
}
